# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8d7f436a1a7878ec125500dc4f376bd39f394f11ee83b992df95ded72940d78fc4d62be9d695e0c41d971313a5fa9d24565814b9efed018f05a0644c746f44

test:
  secret_key_base: 9ac49bcbafcd94b1190695cf3f7db9f4884203d5ab2900ed59c71c0ebb692fbd6a2e08cd3cd70521cf2c232e64315226e91365a48cd9508ac98696621031f7e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
